source-builder/config/gdb-common-1.cfg: Fix building with Python 3.8
Starting with Python 3.8, python3-config requires the "--embed" flag to
print the flags required for embedding Python in an application.

Fixes:
error: shell macro failed: /home/anders/work/rtems/rsb/source-builder/sb/rtems-build-dep -c gcc  -l : 2: error: no library (-l) provided

Signed-off-by: Anders Montonen <Anders.Montonen@iki.fi>