Use 4.11 branch for rtems-tools automake patch URL
The automake-1.12.6-bugzilla.redhat.com-1239379.diff patch used for the
4.11 toolchain does not exist in the "5" branch in the rtems-tools
repository, but does exist in the "4.11" branch, so change the URL used
to get rtems-tools files to use the "4.11" branch instead.

This should resolve errors like this in the build:

  Creating source directory: patches
  download: https://gitlab.rtems.org/rtems/tools/rtems-tools/-/raw/5/tools/4.11/automake/automake-...<see log> -> patches/automake-1.12.6-bugzilla.redhat.com-1239379.diff
  download: https://gitlab.rtems.org/rtems/tools/rtems-tools/-/raw/5/tools/4.11/automake/automake-...<see log>: error: HTTP Error 404: Not Found
  error: downloading https://gitlab.rtems.org/rtems/tools/rtems-tools/-/raw/5/tools/4.11/automake/automake-1.12.6-bugzilla.redhat.com-1239379.diff?h=4.11: all paths have failed, giving up
  Build FAILED
    See error report: rsb-report-automake-1.12.6-x86_64-linux-gnu-1.txt
  error: downloading https://gitlab.rtems.org/rtems/tools/rtems-tools/-/raw/5/tools/4.11/automake/automake-1.12.6-bugzilla.redhat.com-1239379.diff?h=4.11: all paths have failed, giving up
  Build Set: Time 0:00:08.019691
  error: downloading https://gitlab.rtems.org/rtems/tools/rtems-tools/-/raw/5/tools/4.11/automake/automake-1.12.6-bugzilla.redhat.com-1239379.diff?h=4.11: all paths have failed, giving up
  Build Set: Time 0:00:08.020617
  error: downloading https://gitlab.rtems.org/rtems/tools/rtems-tools/-/raw/5/tools/4.11/automake/automake-1.12.6-bugzilla.redhat.com-1239379.diff?h=4.11: all paths have failed, giving up
  Build Set: Time 0:00:08.022781
  Build FAILED